# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run:  mvn clean package
    - name: creating docker image
      run:  docker build -t demoimage .
    - name: login to azure
      run:  az acr login --name wmtacr -p yUnhOmvkGnVl6kXe3ryfJ5KKJO/Hfxao -u wmtacr
    - name: tag the docker image
      run:  docker tag demoimage wmtacr.azurecr.io/samples/demoi
    - name: push the docker image to ACR
      run:  docker push wmtacr.azurecr.io/samples/demoimage


    
      
